<a href="https://colab.research.google.com/github/suraj-safi1/Count_With_Tuples/blob/main/teachingnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas


In [ ]:
pip install numpy


In [ ]:
import numpy as np
height=np.array([100,123,234,79,109])

In [ ]:
type (height)

numpy.ndarray

In [ ]:
height[2]

79.0

In [ ]:
print(height[0:3])

[100 123 234]


In [ ]:
a=np.ones([3,4])
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
np.mean(height)

129.0

In [ ]:
sum(height)/len(height)

129.0